# Generated by Django 4.0.6 on 2022-07-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
